setup.py

This tells distutils/setuptools that the package is platform-specific,
because it has a C-extension. This is used, for example, by bdist_wheel
to indicate the specific platform instead of creating a generic wheel.

More setup.py tweaks to make wheel building work better

---

dynd/include/copy_from_numpy_arrfunc.hpp
dynd/include/copy_to_numpy_arrfunc.hpp
src/array_as_numpy.cpp
src/copy_from_numpy_arrfunc.cpp
src/copy_to_numpy_arrfunc.cpp

Instead of having the dual-mode instantiate as it was, the arrfunc
at the core of these copy operations is now just for one numpy element
to/from one dynd element. This arrfunc is lifted via elwise, and
the setup code for the dynd-like array like "Fixed * Fixed * void"
to represent a 2D NumPy array, for example, is now moved out into
the helper function which calls the arrfunc.

Fix up copy_to_numpy and copy_from_numpy to reflect elwise refactor

---

CMakeLists.txt
dynd/include/array_as_numpy.hpp
dynd/include/array_as_pep3118.hpp
dynd/include/array_as_py.hpp
dynd/include/array_assign_from_py.hpp
dynd/include/array_from_py.hpp
dynd/include/array_from_py_dynamic.hpp
dynd/include/array_from_py_typededuction.hpp
dynd/include/array_functions.hpp
dynd/include/arrfunc_from_pyfunc.hpp
dynd/include/arrfunc_functions.hpp
dynd/include/config.hpp
dynd/include/copy_to_numpy_arrfunc.hpp
dynd/include/ctypes_interop.hpp
dynd/include/eval_context_functions.hpp
dynd/include/exception_translation.hpp
dynd/include/gfunc_callable_functions.hpp
dynd/include/git_version.hpp
dynd/include/init.hpp
dynd/include/numpy_interop.hpp
dynd/include/py_lowlevel_api.hpp
dynd/include/type_functions.hpp
dynd/include/utility_functions.hpp
dynd/src/init.cpp
setup.py

Main changes:
Add PYDYND_API symbol to indicate which functions should be exported by the .dll.
The NumPy symbols were missing, causing link errors. Added the import_numpy to pydynd_init.

Fix building of pydynd and Cython modules on Windows MSVC

---

setup.py

This installs some additional headers and pxd files that are needed to use dynd-python declarations in other modules.

Install additional files and headers

---

.travis.yml

I figured that, in light of https://github.com/libdynd/libdynd/pull/487, it would make sense to do that here too. This should hopefully speed up the build even more.

Skip installing numpy since the default version is recent enough.

---

dynd/config.pyx
dynd/cpp/config.pxd

This is a small follow up to the pxd restructuring in https://github.com/libdynd/dynd-python/pull/321. I noticed I missed a pair of declarations while working on some of the code for issue https://github.com/libdynd/dynd-python/issues/331.

Move libdynd version string declarations to cpp declaration files.

---

dynd/src/exception_translation.cpp

This fixes the test failure from https://github.com/libdynd/libdynd/pull/536. Generic `dynd::dynd_exception` instances weren't getting caught since they are no longer subclasses of `std::exception`.

Added extra exception catching branch

---

dynd/src/array_as_pep3118.cpp

This fixes the previous issues with uncaught c++ exceptions getting thrown during the tests. This PR matches dynd-python to https://github.com/libdynd/libdynd/pull/538.

Match exception changes in libdynd

---

BUILD_INSTALL.md

In part 5 of the build from source dynd-python is said to require a `sudo make install` step, but https://github.com/libdynd/dynd-python/issues/370#issuecomment-143808702 suggests it should be `python setup.py install`.
Also — this eliminates sudo from at least one step (which should be fine)? I'll change it to include sudo if that can be expected to fail in most situations.

Fix install instructions to setup.py in

---

dynd/config.pxd
dynd/config.pyx
dynd/include/exception_translation.hpp

As a part of the restructuring, I'm trying to make it so that all initialization happens implicitly as a part of each Python modules initialization routine.

Remove initialization function for BroadcastError.

---

dynd/__init__.py

Give preference to dlls on the path over dlls in the default install
location.
Complain very loudly in the fallback search if the runtime environment
isn't sane enough to have various system default environment variables
set.

Refine libdynd.dll search order.

---

dynd/cpp/type.pxd
dynd/ndt/type.pyx

This updates dynd to match https://github.com/libdynd/libdynd/pull/974.  The type functions appear to be unused, so I've removed them all.

Remove type functions.

---

setup.py

It looks like I missed this in https://github.com/libdynd/dynd-python/pull/416, so here's a fix along with a little control flow cleanup.

Properly handle multiple extra cmake arguments on non Windows platforms.

---

dynd/include/exception_translation.hpp

This at least prevents crashing the interpreter when an exception somehow gets through all the other layers of exception translation we have set up. Usually if something manages to get through all those other layers it indicates a toolchain problem or possibly a version mismatch between libdynd and dynd-python, but this lets us raise an error on the Python side of things anyway.

Add generic exception handling block to exception translation routine.

---

dynd/include/assign.hpp
dynd/include/copy_from_numpy_arrfunc.hpp
dynd/src/assign.cpp
dynd/src/copy_from_numpy_arrfunc.cpp

Update Python bindings to match https://github.com/libdynd/libdynd/pull/990.

Update Python-specific callables to use the new declfunc template.

---

cmake/UseCython.cmake

According to https://cmake.org/cmake/help/v3.0/command/add_custom_target.html this helps make sure custom commands are routed properly through the various layers of makefiles in the build system.

Add verbatim to improve cross-platform compatibility of Cython CMake interop

---

dynd/cpp/array.pxd
dynd/cpp/irange.pxd

This fills in a few extra pieces necessary to make the C++ `nd::array` class minimally usable from within Cython.

Pxd extras

---

dynd/cpp/array.pxd
dynd/cpp/type.pxd
dynd/nd/array.pyx
dynd/ndt/type.pyx

Update for the changes in #1009.

Use the new type properties from libdynd.

---

dynd/cpp/array.pxd
dynd/nd/array.pyx

This is an update for the change in #1013 (libdynd).

Array property may now raise std::invalid_argument().

---

dynd/__init__.py

This allows the custom dll loading logic to pick up libdyndt as well as libdynd.

Dll load logic

---

dynd/include/type_functions.hpp
dynd/ndt/type.pyx

For the purpose of documenting the current state of libdynd's type system it would be great to remove all ambiguities.  In this case I'm not sure if other encodings apart from utf-8 were planned on the Python level.

libdynd strings always have utf-8 encoding.

---

.travis.yml
BUILD_INSTALL.md
conda.recipe/meta.yaml
postprocess.py

This makes Cython version 0.24 required. That release includes a variety of very relevant bugfixes.

Cython Update

---

cmake/UseCython.cmake
setup.py

This fixes a few small issues with the incremental build on Windows. When using a version of Cython recent enough to have https://github.com/cython/cython/pull/513 this makes incremental builds work. It's still probably not as fast as it ought to be since CMake is run each time, but this prevents the C++ compiler from getting called unnecessarily.

Incremental build

---

.travis.yml
CMakeLists.txt
appveyor.yml
conda.recipe/build.sh
conda.recipe/meta.yaml
dynd/config.pyx
dynd/include/array_from_py.hpp
dynd/include/do_import_array.hpp
dynd/include/numpy_interop.hpp
dynd/include/numpy_interop_defines.hpp
dynd/include/numpy_type_interop.hpp
dynd/include/type_deduction.hpp
dynd/nd/array.pxd
dynd/nd/array.pyx
dynd/nd/callable.pxd
dynd/nd/callable.pyx
dynd/ndt/type.pxd
dynd/ndt/type.pyx
dynd/src/array_from_py.cpp
dynd/src/init.cpp
dynd/src/numpy_interop.cpp
dynd/src/numpy_type_interop.cpp
dynd/src/type_deduction.cpp

This breaks up some of the numpy interop code so that the type module doesn't have any cython-level dependencies on the array module.
The type module still has to use array_conversions.cpp to provide the check for whether or not something is an array in the type deduction code. That'll have to be replaced by some sort of dynamic machinery as well.

Remove cython-level dependency of type module on array module

---

CMakeLists.txt
cmake/FindLibDyND.cmake

Slight cleanup of https://github.com/libdynd/dynd-python/pull/689.

Stop linking type modules against libdynd

---

CMakeLists.txt

Cmake-3.5.1 needs this (I had accidentally removed this line in the previous linkage patch).

Fix dependencies (cmake-3.5.1).

---

dynd/__init__.py
dynd/common/__init__.py
dynd/nd/__init__.py
dynd/nd/test/__init__.py
dynd/nd/test/__main__.py
dynd/ndt/__init__.py
dynd/ndt/test/__init__.py
dynd/ndt/test/__main__.py
setup.py

This (explicit) namespace package works here on Linux/Windows with both Python 2 and Python 3.
The magic switch is in setup.py:
1) DIST_TARGET = 'all' -> The existing install.
2) DIST_TARGET = 'ndt' -> Install only libdyndt and the ndt module.
3) DIST_TARGET = 'nd' -> Install only libdynd and the nd module.
Options 1) and 2) are self-contained, 3) depends on 2).

Namespace package

---

dynd/cpp/type.pxd
dynd/include/array_conversions.hpp
dynd/include/type_conversions.hpp
dynd/include/type_deduction.hpp
dynd/ndt/__init__.py
dynd/ndt/type.pyx
dynd/src/array_from_py.cpp
dynd/src/assign.cpp
dynd/src/type_conversions.cpp
dynd/src/type_deduction.cpp

Bugfixes to bring dynd-python into sync with https://github.com/libdynd/libdynd/pull/1254. Several bits of random cleanup that I took care of along the way are also included.
We should discuss what the best way is to map type ids back to types (or how to eliminate a few remaining cases where that needs to happen). Here I ended up having to use `dynd::ndt::infos()` in a few places, and that seems less than ideal.

Remove calls to type constructors removed in libdynd

---

dynd/__init__.py
dynd/common/__init__.py
dynd/nd/__init__.py
dynd/ndt/__init__.py
setup.py

This adds a --target argument to setup.py.  It would be great to have this in because it avoids some ugly hacks in the conda build that I'm working on.
The --target argument is pre-parsed and removed from sys.argv. The rest of the args is passed on to build_ext/install/build as usual.
The diff also contains all changes from https://github.com/libdynd/dynd-python/pull/710 , which should go in first.

Setup target arg

---

setup.py

Remove dependence on os.path.samefile for Python 2.7 on Windows.

---

.travis.yml
conda/nd.recipe/meta.yaml
conda/ndt.recipe/meta.yaml

Installing a package from a file url is broken in conda 4.1.8, but it's
not something we actually need for our tests anyway.
Should work around https://github.com/conda/conda/issues/2845#issuecomment-233145892.

Use conda build exclusively to test installation.
