src/array_as_py.cpp
src/array_assign_from_py.cpp
src/copy_from_numpy_arrfunc.cpp
src/copy_to_numpy_arrfunc.cpp

This change removes direct calls to an arrfunc instantiate,
instead going through the standard call mechanism. It is based
on a bit of a hack which wraps the data in a temporary nd::array.
It would be nice to create a skeleton array object for this
purpose, which acts like nd::array but owns no references, relying
on ownership borrowed from others.

Change the calls to the python bindings arrfuncs

---

dynd/include/kernels/copy_to_pyobject_kernel.hpp
dynd/src/copy_from_pyobject_arrfunc.cpp
dynd/src/copy_to_pyobject_arrfunc.cpp

[WIP] Arrfunc

---

dynd/include/copy_to_numpy_arrfunc.hpp
dynd/include/kernels/apply_pyobject_kernel.hpp
dynd/include/kernels/copy_from_numpy_kernel.hpp
dynd/include/kernels/copy_from_pyobject_kernel.hpp
dynd/include/kernels/copy_to_pyobject_kernel.hpp
dynd/include/kernels/numpy_ufunc.hpp
dynd/src/copy_from_numpy_arrfunc.cpp
dynd/src/copy_to_numpy_arrfunc.cpp

Removed arrfunc_type from instantiate.

[WIP] Instantiate

---

CMakeLists.txt
dynd/nd/array.pxd
dynd/nd/array.pyx
dynd/nd/arrfunc.pxd
dynd/nd/functional.pxd
dynd/nd/functional.pyx
dynd/ndt/__init__.py
dynd/ndt/type.pxd
dynd/ndt/type.pyx
setup.py

[WIP] Functional

---

appveyor.yml
setup.py

It now builds/runs/passes tests.

Fix up how the built extension paths are constructed

---

.travis.yml

Resolves https://github.com/libdynd/dynd-python/issues/341.

Test against numpy 1.7.2 in Travis build.

---

dynd/include/gfunc_callable_functions.hpp

Update dynd-python for gcallable renaming

---

setup.py

Fixes a bug I accidentally introduced on Friday.

Fix bad routing of cmake command.

---

CMakeLists.txt
dynd/__init__.py
dynd/include/arrfunc_functions.hpp
dynd/include/visibility.hpp
dynd/include/wrapper.hpp
dynd/src/wrapper.cpp
setup.py

These are the minimal changes necessary to get everything working on Windows. A lot of refactoring still needs to be done, but it was best to just get things working again first.

Visibility

---

CMakeLists.txt
cmake/FindLibDyND.cmake
conda.recipe/bld.bat
conda.recipe/meta.yaml
setup.py

This contains some refactoring needed to enable the conda build on Windows.

Conda build

---

dynd/nd/array.pxd
dynd/nd/array.pyx
dynd/nd/callable.pxd
dynd/nd/callable.pyx
dynd/ndt/type.pxd
dynd/ndt/type.pyx

This is a follow up to the fast instantiations PR (https://github.com/libdynd/dynd-python/pull/403) that works around the issue causing the segfaults there.

Conversions to and from c++ types

---

appveyor.yml
conda.recipe/meta.yaml

Return exit code when running dynd's python tests

---

.travis.yml

This is a follow up to https://github.com/libdynd/dynd-python/pull/445/files that applies a similar set of changes for the Travis CI build.

Prevent false positives when running Travis CI tests

---

BUILD_INSTALL.md
README.md

Also update build instructions.

[ci-skip] Document changes in supported Python versions.

---

dynd/cpp/func/callable.pxd
dynd/include/arrfunc_functions.hpp
dynd/nd/array.pxd
dynd/nd/array.pyx
dynd/nd/callable.pyx
dynd/nd/functional.pyx
dynd/ndt/type.pxd
dynd/ndt/type.pyx
dynd/src/arrfunc_functions.cpp
dynd/tests/test_dtype.py

There's an infinite recursion issue here I'm going to tackle in a separate PR before continuing with this.

Port callable_call to Cython.

---

dynd/cpp/array.pxd
dynd/cpp/type.pxd
dynd/nd/array.pyx

This syncs dynd with https://github.com/libdynd/libdynd/pull/971.  It should be applied on top of #592.

Update dynd to use nd::array::get_functions()

---

dynd/cpp/array.pxd
dynd/cpp/type.pxd
dynd/nd/array.pyx

This synchronizes dynd with https://github.com/libdynd/libdynd/pull/970.  (The tests currently segfault here on Linux, but I think they also did before this change.)

Update dynd to use nd::array::get_properties().

---

CMakeLists.txt
cmake/FindLibDyND.cmake
dynd/nd/array.pyx
setup.py

This should fix the dynd-python build once https://github.com/libdynd/libdynd/pull/1028 and https://github.com/libdynd/libdynd/pull/1029 are merged.

Cmake config

---

dynd/tests/test_unicode.py

This should be applied after https://github.com/libdynd/libdynd/pull/1094 in order to test the string properties.

Add tests for various encoding properties.

---

dynd/include/type_functions.hpp
dynd/ndt/type.pyx
dynd/tests/test_dtype.py
dynd/tests/test_type_basics.py
dynd/tests/test_unicode.py

This fixes https://github.com/libdynd/libdynd/issues/1093 and should also update dynd-python for https://github.com/libdynd/libdynd/pull/1098 .
Additionally, it also contains the changes from https://github.com/libdynd/dynd-python/pull/631 .

Fix type representation

---

.gitignore
CMakeLists.txt
devdocs/README.md
devdocs/pyobject-conversion.md
setup.py

The code for "python setup.py develop" also snuck its way in here.

Design document for pyobject conversion code

---

.gitignore
devdocs/pyobject-conversion.md

Added examples of what pyobject -> nd::array should do.

More to Python/DyND object conversion doc

---

CMakeLists.txt
cmake/FindLibDyND.cmake

This is the same as https://github.com/libdynd/dynd-python/pull/670 with a clean history.

Link dynd.ndt against libdyndt only.

---

CMakeLists.txt
cmake/FindLibDyND.cmake

Reverts libdynd/dynd-python#674

Revert "Link dynd.ndt against libdyndt only."

---

.travis.yml
appveyor.yml
buildscripts/bdist_wheel.sh
conda/nd.recipe/bld.bat
conda/nd.recipe/build.sh
conda/nd.recipe/meta.yaml
conda/ndt.recipe/bld.bat
conda/ndt.recipe/build.sh
conda/ndt.recipe/meta.yaml
setup.py

First attempt at building conda dynd.nd and dynd.ndt packages.

Build namespace packages

---

conda/ndt.recipe/bld.bat

Currently debugging the CI build via repeated force-push. I haven't solved the issue yet.

Fix Appveyor test failures

---

appveyor.yml
conda/nd.recipe/bld.bat
conda/nd.recipe/build.sh
conda/nd.recipe/meta.yaml
conda/ndt.recipe/bld.bat
conda/ndt.recipe/build.sh
conda/ndt.recipe/meta.yaml

WIP: cleaning up the current conda recipes and CI builds.

Update conda recipes
